# Read the docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and othe rtools you might need
build:
  os: ubuntu-24.04
  tools:
    ruby: "3.3"

  commands:
    # Install dependencies
    - gem install bundle
    - bundle install
    # Build the site and save geerated files into Read The Docs directory
    - jekyll build --destination $READTHEDOCS_OUTPUT/html